### ISSUE TITLE
[BUG] "Show Robux" setting does not hide Robux button from navigation header when disabled

### ISSUE THREAD

**Issue by Mystyle-48** [AntiBoomz/BTRoblox#101]
![Screenshot 2024-05-23 141603](https://github.com/AntiBoomz/BTRoblox/assets/89315313/66832141-82c0-4aec-a494-83636e8c50f8)

**Comment by AntiBoomz** [comment]
Thanks for the report, this was fixed a few weeks back in c5129814e87f474b14660cce109bce15cc05d3aa, but the fix hasn't been pushed out to users yet. If everything goes to plan, the fix should be pushed to users within a few days.

**Comment by AntiBoomz** [comment]
The fix has been out for a while now, closing the issue.
