### ISSUE TITLE
[BUG] Show more friends option no longer works

### ISSUE THREAD

**Issue by K4rlox** [AntiBoomz/BTRoblox#110]
Browser: Opera GX
show more friends option no longer shows more friends even when all the extensions related to roblox website is removed or disabled, a full reset of the extension does not work
![image](https://github.com/user-attachments/assets/c271eb70-3d8a-4e10-9f93-668ffa1d0c47)

**Comment by gronk08** [comment]
it doesnt work for me either in chrome, I refreshed and everything and its still the same
