### ISSUE TITLE
BTR displays "no friends" on Roblox Profiles

### ISSUE THREAD

**Issue by restarrt** [AntiBoomz/BTRoblox#112]
Going on any Roblox profile, it is shown that the user has no friends, but going to the actual friends list page shows the friends.
![image](https://github.com/user-attachments/assets/daa8cbfd-746e-4db2-a595-9dfd4fdf697a)
![image](https://github.com/user-attachments/assets/387c4d55-04e5-4c16-9c17-a6f0912cdcab)

**Comment by restarrt** [comment]
I'm on a chromium browser, if it helps.

**Comment by ceat-ceat** [comment]
same behavior in firefox
