### ISSUE TITLE
Fast User Search not suggesting friends

### ISSUE THREAD

**Issue by LandoMangus** [AntiBoomz/BTRoblox#114]
works for normal users, but wont suggest friends once typing in part of their username

/
![image](https://github.com/user-attachments/assets/0b3d8177-ca38-4609-823f-93981d650f57)
![image](https://github.com/user-attachments/assets/90ca4cd7-503c-4e1d-8ad9-3aa0f10a6701)

**Comment by LandoMangus** [comment]
also tested this problem on edge, and firefox. both had the same result

**Comment by NobleDraconian** [comment]
Getting the same issue here on chrome, it broke as of yesterday.

**Comment by p4rasubtw** [comment]
![image](https://github.com/user-attachments/assets/ed8adcd6-680b-4cf9-9cfb-1165ab67655c)
This is whats causing it, Hopefully BTRoblox comes up with a bypass bcz this feature is really unnecessary and dogshit

**Comment by LandoMangus** [comment]
this did happen before that update came out. but if it was the problem, id just get rid of the circle to show if anybody is offline/online once getting their username suggested.

![image](https://github.com/user-attachments/assets/02717395-1169-40a5-890f-0bec9cb79c08)

it might not be as simple as that, but just a suggestion

**Comment by AntiBoomz** [comment]
Closed as fixed.
