### ISSUE TITLE
Last online stuck for ALL users! (API updated)

### ISSUE THREAD

**Issue by Thiago3246** [AntiBoomz/BTRoblox#115]
So, when i go to every roblox profile, last online remains 'online now' if the person is online, but if offline, it's stuck at "Nov 15, 2024 | 2:00 AM (GMT-3)

Screenshots: (First is Roblox profile, second is my lost account)
![image](https://github.com/user-attachments/assets/d885cf87-082c-4fa7-8346-44852d720638)
![image](https://github.com/user-attachments/assets/10a5d8b6-a0ae-4746-acb8-176064c3665a)

**Comment by Thiago3246** [comment]
i tested in Edge browser, with only ropro extension, and got the same problem! I think roblox updated something
![image](https://github.com/user-attachments/assets/1830c3f7-46f5-4910-9a68-00c5dd490453)

**Comment by p4rasubtw** [comment]
![image](https://github.com/user-attachments/assets/06db7ec1-55d6-48e0-bc3f-d6dbc4bc3671)
hopefully BTRoblox comes up with a bypass, because this update was really unnecessary and dogshit

**Comment by AntiBoomz** [comment]
Closed as the feature was removed in the last update.
