### ISSUE TITLE
Fast search not working on Opera GX

### ISSUE THREAD

**Issue by nikilord7** [AntiBoomz/BTRoblox#120]
This is Chrome
![image](https://github.com/user-attachments/assets/9b0493c0-6364-4bc6-9f1d-c75409c7a90b)

This is Opera
![image](https://github.com/user-attachments/assets/e9dd9f75-fcab-4349-a2f3-5e0bf9cd4bfe)

**Comment by CursedGhoul** [comment]
Doesn't Opera GX take it from the google thing. I don't think it was ever made to work on Opera

**Comment by Reset5099** [comment]
i'm also having the same issue but in Chrome
i think i have this issue for weeks, ill try to find a fix

![image](https://github.com/user-attachments/assets/0331586d-bf94-4913-9db8-2ebc21edbc0a)

**Comment by CursedGhoul** [comment]
Works fine for me on Chrome 131
![Screenshot 2024-12-14 112741](https://github.com/user-attachments/assets/5072d68d-8975-49be-bedc-352930f6ae78)

**Comment by AntiBoomz** [comment]
It'll probably be a while before the fix (84343588c553eb843f13becb2847d9c8aa8020ad) for this will go out, but for now you can fix the issue by running this line of code in the browser's developer tools console (right click anywhere on the roblox page, press inspect and open the console tab):
`localStorage.removeItem("BTRoblox:fastsearchCache")`

**Comment by nikilord7** [comment]
Alright thanks.
