### ISSUE TITLE
Group Shout Notifications not working correctly

### ISSUE THREAD

**Issue by zShahin** [AntiBoomz/BTRoblox#22]
Hello! I've just recently gotten the problem that the Group Shout is not working correctly, I don't get a Notification (Pop-up) and don't get a Sound, Idk if it is just me. I have already reset my browser (Opera) and it seems like it still doesn't work.

**Comment by AntiBoomz** [comment]
Unable to reproduce issue.

Opera Version: 66.0.3515.103
BTRoblox Version: 2.13.1 (Installed through chrome web store)

**Comment by zShahin** [comment]
The problem also started at my friend, he doesn't get any Notifications anymore
