### ISSUE TITLE
Context Menu to copy Group Role ID/Rank Number

### ISSUE THREAD

**Issue by LewisTehMinerz** [AntiBoomz/BTRoblox#23]
We have group ID copying, so I believe we should have group role ID/rank number copying as well. It's a special use case but sometimes I use it. Rank numbers are probably the more useful of the two but I'd like to have both just in case.

The dropdown items have an `id` attribute of `role-<ID>` so it'll probably require you to strip of the `role-` portion to get the true ID.

Rank numbers need to be requested using https://api.roblox.com/groups/<id> it appears, I don't see a way of getting it from the page unfortunately. Could be accomplished by making the request when the group page is loaded and then getting the data later on for use in the context menu.

**Comment by AntiBoomz** [comment]
Added in c9556af11d38fd3f87427c48a1b74b41a35de412
