### ISSUE TITLE
Download all option freezes up or crashes Chrome tab.

### ISSUE THREAD

**Issue by iialexidai** [AntiBoomz/BTRoblox#30]
The download all versions option tends to get stuck on the last or second to last version of the game. It also tends to crash the Chrome tab with a ram usage error.

**Comment by AntiBoomz** [comment]
Feature was removed in 3a8dd3b9ff29028db1b0ac423130f710f6f43d1e

**Comment by ChipioIndustries** [comment]
Out of curiosity, why was this removed? I found it really useful for archiving my projects.

**Comment by iialexidai** [comment]
It basically acted like a giant memory leak with the way files were
downloaded. It caused instability with browsers. Too much work to fix most
likely I created my own nodejs tool to download places.

**Comment by ChipioIndustries** [comment]
Would you be willing to share that?
