### ISSUE TITLE
Change Roblox Favicon

### ISSUE THREAD

**Issue by ghost** [AntiBoomz/BTRoblox#32]
It would be cool if we could change the Roblox Favicon to Red or even upload our own icons. It's not that visible in browser dark modes  and it just doesn't look good.

**Comment by scrapter** [comment]
This is **NOT** possible afaik.

**Comment by qfoxb** [comment]
Here to say that this is **COMPLETELY** possible afaik. this is a userscript i made when i got bored
![image](https://user-images.githubusercontent.com/42038239/197377323-5e3c730a-0f01-4567-9e3f-71e6f1e3ae63.png)

**Comment by 264bpm** [comment]
@ItsClockworky So you're saying it's impossible to change the favicon with an extension? You do not know anything about extensions...
