### ISSUE TITLE
Badge names don't appear when Game Details enhancements are on 

### ISSUE THREAD

**Issue by ajs256** [AntiBoomz/BTRoblox#34]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/67526318/108280586-46cc5880-7133-11eb-917a-8e65dfdd03dd.png">
https://www.roblox.com/games/590744701/RBLXWare

BTRoblox 2.17.5, 2/17/2021
Firefox Stable 85.0.2 (64-bit)
macOS 11.1

**Comment by AntiBoomz** [comment]
Was fixed in ed9076cd3d21649c2029f60c09476a0c2599aede

**Comment by ajs256** [comment]
Thanks! 😃
