### ISSUE TITLE
Unable to read/edit my own UserDescription

### ISSUE THREAD

**Issue by ChipioIndustries** [AntiBoomz/BTRoblox#36]
Tonight's web release of Roblox broke the ability to view my bio on my profile page or edit it on the settings page.
![image](https://user-images.githubusercontent.com/53354220/108945315-42aba980-7611-11eb-8cd1-b27ef6f0a0fb.png)

The console gives this error:
![image](https://user-images.githubusercontent.com/53354220/108945438-771f6580-7611-11eb-9b78-68ebdb6df9f3.png)
(It's worth noting that user statuses were removed in this same release, so this error could be related to that)

This seems to be caused by a new feature that allows users to edit their bio directly on the profile page without having to go to the settings menu:
![image](https://user-images.githubusercontent.com/53354220/108945567-acc44e80-7611-11eb-9581-3bb5a5517997.png)
![image](https://user-images.githubusercontent.com/53354220/108945579-b0f06c00-7611-11eb-9569-76b196a7c07d.png)

**Comment by AntiBoomz** [comment]
Fixed in bcf0de656ffaaef715f75fa51a6059be5b37e1fe de07100eb36919020b41112248f8632fcce014ed
