### ISSUE TITLE
Non-square group icons break profile page

### ISSUE THREAD

**Issue by ajs256** [AntiBoomz/BTRoblox#37]
As seen [here](https://www.roblox.com/users/4142440/profile/)

<img width="570" alt="image" src="https://user-images.githubusercontent.com/67526318/113496474-be213600-94ae-11eb-9a61-bacdfad83f38.png">

**Comment by AntiBoomz** [comment]
Fixed in c1a3755a811237b0f83788a7a69db2c7e0f7ff7e
