### ISSUE TITLE
Group walls fail to load

### ISSUE THREAD

**Issue by ChipioIndustries** [AntiBoomz/BTRoblox#40]
When BTRoblox is enabled the group wall never loads its messages.

![image](https://user-images.githubusercontent.com/53354220/129759582-bc396d32-666b-4369-8af4-bc971fff0409.png)

![image](https://user-images.githubusercontent.com/53354220/129759466-a8297f1a-bb89-4e96-aed1-c92124066c2c.png)

![image](https://user-images.githubusercontent.com/53354220/129759536-940e985f-0d7c-4a5a-a5f0-d83c018a7849.png)

**Comment by AntiBoomz** [comment]
Fixed in 2239cc348b8462f1262b264b4b2b46702424d50a
