### ISSUE TITLE
Server List Pager not showing

### ISSUE THREAD

**Issue by Notable2** [AntiBoomz/BTRoblox#52]
server pager not showing it just shows the normal "load more"
![image](https://user-images.githubusercontent.com/101866725/158978330-0bebc58e-f1a9-4225-8547-a4adb9740a61.png)
![image](https://user-images.githubusercontent.com/101866725/158978372-842ad3c9-4f47-4164-a7c9-8ef671290dbc.png)

**Comment by juNstring** [comment]
same issue, hope they fix it

**Comment by Apple-head94** [comment]
I think Roblox changed their server list according to Ropro, hence why it's broken

**Comment by AntiBoomz** [comment]
Fixed in d11ba24a2e0d3e29ce8ed5d6e4426c9c54166ad3

**Comment by juNstring** [comment]
> Fixed in [d11ba24](https://github.com/AntiBoomz/BTRoblox/commit/d11ba24a2e0d3e29ce8ed5d6e4426c9c54166ad3)

still not showing

**Comment by juNstring** [comment]
> Fixed in [d11ba24](https://github.com/AntiBoomz/BTRoblox/commit/d11ba24a2e0d3e29ce8ed5d6e4426c9c54166ad3)

it's broke u bozo, fix your shit

**Comment by AntiBoomz** [comment]
Version 3.0.1 (which contains the fix) is now available on Chrome. Firefox is still going through review but should probably be available within a couple days.
