### ISSUE TITLE
Playable Audios

### ISSUE THREAD

**Issue by cccskinv** [AntiBoomz/BTRoblox#54]
As you might know audios are private now as 3/22/2022, and almost of them are no longer playable
so, theres any way to bring the button again?

![unknown](https://user-images.githubusercontent.com/100031567/159553697-350d96e8-1565-4529-a64a-733a4bd0aea9.png)

**Comment by p0s0** [comment]
Sadly, no, there's not. It's impossible, as Roblox has added limitations to this in the API.

**Comment by juNstring** [comment]
> Sadly, no, there's not. It's impossible, as Roblox has added limitations to this in the API.

this update sucks, whatever baited audios (old bypassed) audios still work in-game
for example this one 6929010490
