### ISSUE TITLE
Confirm BTRoblox is safe

### ISSUE THREAD

**Issue by RenanMsV** [AntiBoomz/BTRoblox#61]
Just hours ago a big extension SearchBlox got COMPROMISED and they released a new version that could steal items and robux.

Since I can see BTBlox got updated recently Nov 10 2022. I would like to receive a confirmation that this extension is still safe.
https://twitter.com/Roblox_RTC/status/1595236988533313536

I disabled BTRoblox until furter notice.

**Comment by AntiBoomz** [comment]
I can confirm that all official versions of BTRoblox (linked in the [readme](https://github.com/AntiBoomz/BTRoblox/blob/master/README.md)) are still safe to use.

**Comment by RenanMsV** [comment]
Thank you

**Comment by DJJolty257** [comment]
Thank you much for confirming. I recently had my password changed against my will and it happened to be the version of BTR I had. Gonna' get it from here so I stay safe from now on
