### ISSUE TITLE
Add favorite games to fast search

### ISSUE THREAD

**Issue by AntiBoomz** [AntiBoomz/BTRoblox#7]
Requested by: https://twitter.com/Craether_/status/1015392629989740544

**Comment by SabrinaSimao** [comment]
@AntiBoomz IIRC there is only an API to check if a specific game is favorited by the user, but no way of getting all curent favorites, could you confirm that?

https://games.roblox.com/docs#!/v1

**Comment by scrapter** [comment]
> @AntiBoomz IIRC there is only an API to check if a specific game is favorited by the user, but no way of getting all current favorites, could you confirm that?
> 
> https://games.roblox.com/docs#!/v1

Per this, this wouldn't be useful because Roblox has progressed a lot in providing authentic games on search.
