### ISSUE TITLE
Last online broken

### ISSUE THREAD

**Issue by Anonymousperson0016** [AntiBoomz/BTRoblox#72]
The last online feature on the profile is broken. Roblox might've updated the api for it.

**Comment by AntiBoomz** [comment]
Unable to repro, works fine for me. Make sure you're updated to version 3.3.3 and that the extension has all site access permissions granted.

**Comment by jmkd3v** [comment]
OnlineStatus was already marked for removal and the removal date has passed, but occasionaly it still returns information. They made a new endpoint for last-online info - `presence.roblox.com/v1/presence/last-online`
