### ISSUE TITLE
Downloading version of game from version history

### ISSUE THREAD

**Issue by theendbro1** [AntiBoomz/BTRoblox#78]
After Roblox introduced the new creator dashboard, the download button seem to have disappeared. I don't know if this is an issue or if Roblox intentionally removed it. Its faster to download past version of game automatically than manually.

**Now:**
![image](https://user-images.githubusercontent.com/119431064/230716511-4f91ce4b-7a07-49d9-b3a4-a6f7752f1615.png)

**Before:** (Under ... button there is revert and download button)
![image](https://user-images.githubusercontent.com/119431064/230716608-aaf5ca3f-b59c-4f47-a973-a9b21e8eebb5.png)

**Comment by theendbro1** [comment]
I found some temporary fix, before it's fixed on BTRoblox, It's little bit slower but it works.

https://assetdelivery.roblox.com/v1/asset/?id=🟥&version=🟥

Replace 🟥 with id and version

**Comment by Strana** [comment]
> I found some temporary fix, before it's fixed on BTRoblox, It's little bit slower but it works.
> 
> [https://assetdelivery.roblox.com/v1/asset/?id=🟥&version=🟥](https://assetdelivery.roblox.com/v1/asset/?id=%F0%9F%9F%A5&version=%F0%9F%9F%A5)
> 
> Replace 🟥 with id and version

Thanks so much for providing this temporary workaround!!

I hope this issue gets fixed

**Comment by AntiBoomz** [comment]
Fixed in 145f93810e9f290c28d8e483b329ea250b665e97

Create page support is still a WIP though, so the buttons may or may not be enabled by default in the next update.

**Comment by Strana** [comment]
> Fixed in [145f938](https://github.com/AntiBoomz/BTRoblox/commit/145f93810e9f290c28d8e483b329ea250b665e97)
> 
> Create page support is still a WIP though, so the buttons may or may not be enabled by default in the next update.

So... the fix isn't _really_ out yet, but is still in development for release right? because I don't see any buttons on the version history page or any new updates to the browser extension.

**Comment by Hexcede** [comment]
> Fixed in [145f938](https://github.com/AntiBoomz/BTRoblox/commit/145f93810e9f290c28d8e483b329ea250b665e97)
> 
> Create page support is still a WIP though, so the buttons may or may not be enabled by default in the next update.

I just cloned the extension source myself, and, it doesn't seem like this is working. No download button shows up.

**Comment by AntiBoomz** [comment]
This was released in version 3.4.0 and should be enabled by default.
