### ISSUE TITLE
Extensions keeps having to be reinstalled every time.

### ISSUE THREAD

**Issue by Compwnter** [AntiBoomz/BTRoblox#81]
This has been happening for some time now and from what I've heard it isn't just a me thing.
The bug is very self explanatory. The extension just keeps having to be reinstalled from time to time.
I think it's every time you launch your browser again but I could be wrong.
Please fix this bug when possible because it's quite the inconvenience having to reinstall it all the time.

**Comment by AntiBoomz** [comment]
This is an issue with the Brave browser as far as I know. Partially fixed this (and added a warning label in settings if the issue is detected) in e57bfafa290e1082c52b8a7384ccbfc7ef8bd70d
