### ISSUE TITLE
How do I get the github version of BTR to work with chrome?

### ISSUE THREAD

**Issue by halabuba** [AntiBoomz/BTRoblox#82]
So, Im trying to get the Github version of BTR to work on chrome (Because I'm trying to get the fixed version of BTR that Allows you to download older versions of your game again with Roblox's New create.) 

When I download the zip, extract it and load it through chrome it keeps giving me the error "Could not load manifest." 

So I go back BTR Github's main page and see that I'm supposed to remove "placeconfig.js" from the manifest but i cant find this "placeconfig.js" anywhere in the manifest or in the folder, and the only thing that I found that is related to this "placeconfig" is a .css of it. 

Do i remove that .css or wait for a update to the extension? Im just confused and need help.

**Comment by AntiBoomz** [comment]
You need to rename the relevant manifest (either manifest.chrome.json or manifest.firefox.json) to just manifest.json to run the extension.
