### ISSUE TITLE
[BUG] BTRoblox about section broke after random update for some users

### ISSUE THREAD

**Issue by localfossa** [AntiBoomz/BTRoblox#94]
A section appeared on top of it and buttons are not at correct place in a game's page

**Comment by localfossa** [comment]
![image](https://github.com/AntiBoomz/BTRoblox/assets/74490107/0f7f30fa-4da2-4222-8ae6-728c7998bef8)
Old one
![image](https://github.com/AntiBoomz/BTRoblox/assets/74490107/61f9b1d1-98d5-4194-84cf-3bcd9059f598)
New one
Ignore badges section (it is from another extension and I disabled other extension and it still happens)

**Comment by AntiBoomz** [comment]
Is this still happening? I can't get this to happen to me on any of my accounts.

**Comment by localfossa** [comment]
I think roblox reverted the update (Not sure)

**Comment by localfossa** [comment]
It still happens

**Comment by AntiBoomz** [comment]
This should be fixed for all users.
