### ISSUE TITLE
[BUG] Problem showing user status "[Offline]"

### ISSUE THREAD

**Issue by v1zoy** [AntiBoomz/BTRoblox#96]
The status of roblox users inside their profile is not correct, it will always show **[Offline]** though the person is in Website or In-Game,
Example:
![image](https://github.com/AntiBoomz/BTRoblox/assets/102887636/a09e634e-f8c9-4b62-8f1d-91ea89b5e379)

the person is clearly in-game but it will show a **[Offline]** and Last Active.

**Comment by robloxiandemo** [comment]
This seems to be the case for me as well, and occurs when viewing the profile of users that are in studio as well.

**Comment by jeremylpro** [comment]
i got this issue too, @AntiBoomz please fix this it's so annoying

**Comment by v1zoy** [comment]
Seems like it's fixed now, W.
